baseURL = "https://mokkiklubi.fi/"
languageCode = "fi-fi"
title = "Mökkiklubi"
theme = "alpha"

[params]
  description = "Tervetuloa uuden ajan mökkielämykseen."
  images = ["images/pic01.jpg"]
  author = "Hugo-käännös: [Nelson/Roberto](https://nelsonroberto.com/)"
  copyright = "© 2020 Mökkiklubi"
  design = "Teema: [HTML5 UP](http://html5up.net/)"
  ### mainSections = ["blog"] ###

### Footer Social Media Links ###
[[params.share]]
title = "github"
icon = "fa-github"
link = "https://github.com/profiili/mokkiklubi-site"

### For Pages the .RelPermalink must match the menu .URL
### For sections the name/directory must match the menu .Identifier
[menu]
  [[menu.main]]
    identifier = "tilaukset"
    name = "Tilaukset"
    url = "/tilaukset/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Ajankohtaista"
    url = "/posts/"
    weight = 20
